server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://app:8080/api/;
    proxy_set_header Host $host;
  }

  location /admin/ {
    proxy_pass http://app:8080/admin/;
    proxy_set_header Host $host;
  }

  location /actuator/ {
    proxy_pass http://app:8080/actuator/;
    proxy_set_header Host $host;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
