{
 "title": "Distributed Rate Limiter",
 "refresh": "5s",
 "panels": [
  {
   "title": "Allowed vs Rejected",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (result) (rate(rate_limit_requests_total[1m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Redis Errors",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(rate_limit_redis_errors_total[1m])",
     "legendFormat": "redis_errors"
    }
   ]
  },
  {
   "title": "Redis Lua Latency",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "rate(rate_limit_redis_latency_ms_sum[1m]) / rate(rate_limit_redis_latency_ms_count[1m])",
     "legendFormat": "avg_latency"
    }
   ]
  }
 ]
}